name: rolex-client
channels:
  - conda-forge      # Community packages
  - defaults         # Anaconda defaults
dependencies:
  - python=3.11
  
  # HTTP libraries (conda available)
  - requests>=2.28.0
  - httpx>=0.24.0
  
  # CLI libraries (conda available)
  - click>=8.0.0
  - rich>=13.0.0
  
  # Only pip for packages not available via conda
  - pip
  - pip:
    - ommx>=0.0.21          # Not available via conda 